### PR TITLE
set proper status to MantleBackup

### PR DESCRIPTION
**Pull request by ushitora-anqou**

### CODE REVIEW

**Review by satoru-takeuchi — APPROVED** [review]

**Comment by satoru-takeuchi** [comment]
#32 is merged. Could you rebase this to main branch?

**Comment by ushitora-anqou** [comment]
I actually rebased this PR last week, and it looks like the CI started failing after that. I'll try to figure out what's going wrong.

**Comment by ushitora-anqou** [comment]
I think I could fix the bug. The code changes are as follows: https://github.com/cybozu-go/mantle/compare/8d5161972586d30281d7fcc9cafb0effa86855c8..79c269f46631a851f340d9aae6f457893af188a5

Well, it was a bug like a time bomb :(

**Comment by ushitora-anqou** [comment]
@satoru-takeuchi Could you review this again?

**Review by satoru-takeuchi — APPROVED** [review]

**Comment by ushitora-anqou** [comment]
Thank you for your review!

**Pull request merged**
